name: Comment Diff

on:
  pull_request:
    paths:
      - 'Spreadsheet/**'

jobs:
  comment-diff:
    runs-on: ubuntu-20.04
    defaults:
      run:
        # The following allows for each run step to utilize ~/.bash_profile
        # for setting up the per-step initial state.
        # --login: a login shell. Source ~/.bash_profile
        # -e: exit on first error
        # -o pipefail: piped processes are important; fail if they fail
        shell: bash --login -eo pipefail {0}
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}

    - name: install requirements
      run: |
        pip install --upgrade pip
        pip install daff

    - name: make diff
      run: |
        daff git csv
        git config set --global diff.daff-csv.command "daff diff --git --output-format html --fragment --context 0"
        git remote add target https://github.com/pcdshub/pcds-nalms.git
        git fetch target
        mkdir -p ./pr
        git diff target/${{ github.event.pull_request.base.ref }}...HEAD Spreadsheet/ > pr/diff.txt
        echo ${{ github.event.number }} > ./pr/NR

    - uses: actions/upload-artifact@v4
      with:
        name: diff
        path: pr/ 