name: Process on PR

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  generate-xml:
    runs-on: ubuntu-20.04

    defaults:
      run:
        # The following allows for each run step to utilize ~/.bash_profile
        # for setting up the per-step initial state.
        # --login: a login shell. Source ~/.bash_profile
        # -e: exit on first error
        # -o pipefail: piped processes are important; fail if they fail
        shell: bash --login -eo pipefail {0}

    steps: 
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ssh-key: ${{ secrets.DEPLOY_KEY }}
    - name: install dev-requirements
      run: | 
        pip install --upgrade pip
        pip install --requirement dev-requirements.txt
    - name: check installed packages
      run: | 
        pip list
    - name: dump github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - uses: ./.github/actions/validate_csv
    - uses: ./.github/actions/convert_csv_to_xml
    - name: push to main
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        export PRNUM=$(git log --grep="Merge pull request" --pretty=oneline -1 | sed -En "s/.*#([[:digit:]]+).*/\1/p")
        git add XML/
        git commit -am "CI/MNT: convert csv to xml from PR# $PRNUM"
        ls -R XML/
        git push
